# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo first job in Build
  - job: secondbuildjob
    steps:
    - bash: echo 2nd job in Build
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps:
    - script: echo DevDeploy
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - script: echo QADeployJob
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeploy
    steps:
    - script: echo ProdDeploy

