# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo first job in Build
    - script: echo $(Pipelinelevelvariable)
    - script: echo $(Build.BuildNumber)
    - script: echo $(Build.BuildId)
    - script: echo $(System.DefaultWorking)
    - bash: ls -R $(Build.ArtifactStagingDirectory) 
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          ***/*.yml
          ***/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory) 
  # - job: secondbuildjob
  #   steps:
  #   - bash: echo 2nd job in Build
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeploy
#     steps:
#     - script: echo $(environment)Deploy
# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps:
#     - script: echo $(environment)DeployJob
# - stage: ProdDeploy
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeploy
#     steps:
#     - script: echo ProdDeploy

