trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build 
  jobs:
  - deployment: Buildjob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo deploy in Dev
